### PR TITLE
Temporarily workaround around toolchain bug

### PR DESCRIPTION
**Pull request by gnzlbg**
This PR temporarily works around a toolchain bug.

### CODE REVIEW

**Comment by gnzlbg** [comment]
It appears that all build bots have recently started to fail... been scratching my head with another PR thinking it was my fault for a while... :D 

cc @alexcrichton @SimonSapin @sfackler any ideas of why? maybe its time to move from cross to our own ci...

**Comment by SimonSapin** [comment]
This looks like definitely a Cargo bug, thanks for reporting it upstream at https://github.com/rust-lang/cargo/issues/5708. I think it’s fine to temporarily disable this test if this Cargo bug is blocking some other work. Or maybe temporarily switch to the Beta channel? CC https://github.com/alexcrichton/jemallocator/issues/62

**Comment by gnzlbg** [comment]
I'll merge this to disable those tests temporarily and update the cargo issue upstream with the commit required to reproduce this. I'll send a different PR adding beta build bots for the tier 1 targets.

**Comment by alexcrichton** [comment]
I believe removing `links` should also do the trick (temporarily)

**Comment by gnzlbg** [comment]
Thanks for submitting a fix upstream! I think the two jemalloc-sys tests do not test that much actually, and removing links temporarily sounds dangerous if somebody is depending on jemallocator git :/

**Pull request merged**
