### PR TITLE
Support stable Rust, move `impl Alloc` behind a feature flag

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by gnzlbg** [comment]
LGTM, I'll merge once CI finished.

Would it make sense to, in a future PR, enable alloc trait automatically for nightly toolchains?

**Comment by SimonSapin** [comment]
I think it should not. A project might use Nightly for unrelated features, but still prefer `jemallocator` not to break when the `Alloc` trait changes.

**Comment by gnzlbg** [comment]
Makes sense. Thanks!

**Comment by alexcrichton** [comment]
💯

**Pull request merged**
