### PR TITLE
update jemalloc to jemalloc/dev HEAD

### PR DESCRIPTION
**Pull request by gnzlbg**
This will allow using the new `smallocx` API in a sub-sequent PR.

### CODE REVIEW

**Comment by alexcrichton** [comment]
r=me w/ green CI

**Comment by sfackler** [comment]
I would prefer sticking with actual releases of jemalloc in published jemalloc-sys. Is that the plan here?

**Comment by gnzlbg** [comment]
> Is that the plan here?

No, that was not what I intended/planed. Currently, `jemalloc-sys` tracks the `master` branch of `jemalloc` which always points to the last commit of the last official release. The last time I moved it to the release candidates of the next release as soon as they became available, but when that happens the window for changes is often not very big and mostly concerned about fixing regressions.

The [P0901 API (`alloc_excess`)](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0901r0.html) is now available in `jemalloc`'s `dev` branch. It is unclear whether it will be "stabilized" in the next jemalloc release, but I wanted to start exposing it in `jemallocator`ASAP so that we can easily test it from Rust and report if anything needs changing or whether it satisfies our needs.

**Comment by gnzlbg** [comment]
Plan B here could be to allow choosing the `jemalloc` version with a feature at compile-time, such that the feature that enables the  P0901 API uses a different `jemalloc` version instead. I think we already did something like for a while once, and IIRC the only changes that were needed for this were to update the docker container to contain `git` so that the appropriate `jemalloc` commit can be cloned at `build.rs` time.

**Comment by gnzlbg** [comment]
Any thoughts here?

**Comment by gnzlbg** [comment]
ping - should we close this or discuss this further ?

**Comment by sfackler** [comment]
I feel pretty strongly that the released version of the crate should vendor a real release of jemalloc.

**Comment by gnzlbg** [comment]
Ok. Then i'm closing this. I'll wait for the next jemalloc release to add the experimental APIs to jemallocator, and if they don't suit us, we can always try to adapt them in jemalloc upstream and do a minor release or something.

**Comment by sfackler** [comment]
You can always poke at the unstable features in a branch/fork - I don't see why it'd be necessary to do it in stable releases of the jemallocator crate in particular.

**Pull request closed without merging**
