### PR TITLE
Annotate hot-path with likely/unlikely

### PR DESCRIPTION
**Pull request by gnzlbg**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Does this provide any measureable change in performance? This crate will hopefully compile much sooner on stable than the `likely` intrinsic will become available, so I'd rather not depend on it.

**Comment by gnzlbg** [comment]
It will be easy to test that once the benchmarks are merged. 

I would rather merge the benchmarks first, the ci testing afterwards (with appveyor right afterwards), before doing any major changes performance wise. 

I want to do this change in Rustc, but adding benchmarks and running them in the rustc infrastructure is a pain (without taking into account that just testing whether liballoc there compiles takes ages).

**Comment by gnzlbg** [comment]
So here are the results of `cargo benchcmp`, in one file are the improvements (~2600 benchmarks improved), and in the other are the regressions (~900 benchmarks regressed). My conclusion is that measuring is hard. While there are more improvements than regressions, the results are too noisy, and the improvements are tiny in most cases 1-5ns. Larger improvements and regressions are probably just noise, but there is a trend. 

The main reason why I added this is that this is what `jemalloc` does in its own code everywhere (e.g., [here](https://github.com/jemalloc/jemalloc/blob/dev/src/jemalloc.c#L1786), but that is just one example). 

---

Regarding stabilization, we could revert this once the allocator api is stable, or push towards the stabilization of the likely/unlikely intrinsics. AFAIK the only tunning necessary there is to decide whether they should be safe; every backend exposes them so they should not be controversial and they are used in C and C++, and in some domains, they are widely used.

**Comment by alexcrichton** [comment]
I think I'd like to hold off on this as it doesn't seem like a massive improvement and this is unstable. We can try to push for stabilization of these intrinsics somehow upstream perhaps.

**Comment by gnzlbg** [comment]
I'll write a small RFC for it.

**Comment by gnzlbg** [comment]
These intrinsics are going to be removed from nightly, and an attribute will probably be pursued instead: https://github.com/rust-lang/rust/issues/26179

**Pull request closed without merging**
