### PR TITLE
Don’t assume MIN_ALIGN for small sizes

### PR DESCRIPTION
**Pull request by SimonSapin**
Same as https://github.com/rust-lang/rust/pull/46117

See also discussion of jemalloc’s behavior at https://github.com/jemalloc/jemalloc/issues/1072

### CODE REVIEW

**Comment by gnzlbg** [comment]
@SimonSapin could you check if this use case is covered in #26  ?

If so, it might be good to run the benches on this PR and see if there is a difference, and if so, how big. 

But AFAIK this is required for correctness, is that right?

**Comment by SimonSapin** [comment]
Right, this is correctness fix. The aspect that’s performance-dependent is whether we should go further and remove `MIN_ALIGN` entirely.

**Comment by gnzlbg** [comment]
Makes sense. 

---

FWIW `MIN_ALIGN` is also used [here](https://github.com/SimonSapin/jemallocator/blob/fd99aeeb2dd45ecdd9db1e49ff718e624960c63c/src/lib.rs#L147) to dispatch to `calloc` instead of `mallocx(size, flags | MALLOCX_ZEROED)`, so it might have performance implications beyond the cost of `align_to_flags`.

**Comment by SimonSapin** [comment]
Right, calling `calloc` is probably similar to the `flags == 0` fast path in other jemalloc functions discussed in https://github.com/rust-lang/rust/pull/46117#issuecomment-345733107.

**Comment by gnzlbg** [comment]
@SimonSapin yes I've added a `benches/calloc.rs` that benchmarks `calloc` vs `mallocx( , flags | MALLOCX_ZEROED)`, the differences in most cases is "small", in some cases `mallocx` is faster and in others `calloc` is faster, but you will be able to try for yourself once that is merged. 

Please feel free to review the benchmarks and give me input. Its a lot of boilerplate that I don't seem to be able to avoid because I cannot concatenate identifiers to form new identifiers in macros.

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
