### PR TITLE
[ci] use cross instead of cargo

### PR DESCRIPTION
**Pull request by gnzlbg**
The intent is to easily expand the `ci` to many more targets in subsequent pull-requests.

### CODE REVIEW

**Comment by gnzlbg** [comment]
For some reason the new jemalloc version got pulled into all my PRs ... :(

**Comment by alexcrichton** [comment]
I'd sort of rather not be personally on the hook for all these platforms, I think it's fine to add support but the build script and integration here changes so rarely I don't think there's many worry of regressions. This crate is just a tiny wrapper around jemalloc and it seems a little redundant to basically just be testing jemalloc?

In that so let's say one of these platforms goes red. That means that either (a) the Rust integration is busted or (b) jemalloc is busted. In the case of (a) I think that will *very* rarely happen and we don't need a huge amount of infrastructure on all PRs and commits in the meantime to detect it. In the case of (b) there's nothing we can do anyway but probably report a suboptimal bug upstream without putting tons of effort into reducing it to not relying on Rust. 

In both these cases I'm not entirely thrilled about adding all these platforms :(

**Comment by gnzlbg** [comment]
@alexcrichton I am updating the jemalloc version in another PR and that breaks some platforms, so I'd rather have these tests for all these platforms here with `allow_failures` so that we know when upgrading jemalloc breaks something. 

Right now when we update `jemalloc` we have to update it in rustc, do a test run there, and see what breaks. Ideally, when we move `liballoc_jemalloc` to an external dependency of rustc, like `jemallocator`, we could just test for breakage locally here first. That is, if we update the jemalloc version here and it breaks, chances are, rustc is going to break as well if we upgrade it to a newer jemalloc version.

**Comment by alexcrichton** [comment]
Yes that's true, upgrading jemalloc can cause platform breakage, but again I think I just do not personally want to maintain so many platforms. It'll be our job in rustc to catch these breakages if we'd like.

**Comment by gnzlbg** [comment]
Would you accept PRs that fix broken platforms that are not tested?

**Comment by alexcrichton** [comment]
Yes of course!

**Pull request closed without merging**
