### PR TITLE
Rename no_prefix feature to unperfixed_malloc_on_supported_platforms

### PR DESCRIPTION
**Pull request by SimonSapin**
As proposed in discussion starting at https://github.com/alexcrichton/jemallocator/pull/54#issuecomment-399782432.

This describes what the feature does, including its possibly-unexpected platform-specific aspect.

Avoiding negation in the name also helps argue that this feature is “correct” insofar as Cargo feature flags adding functionality and not removing them, since Cargo selects the union of features requested by multiple dependents.

### CODE REVIEW

**Comment by SimonSapin** [comment]
“Override `malloc`” is meant as implying “Override `malloc` and other related standard symbols such as `free`, etc.”

**Comment by SimonSapin** [comment]
I don’t know what the zone allocator is. Maybe @glandium can say more on this?

**Comment by sfackler** [comment]
The zone allocator is how jemalloc takes over malloc/free on OSX. Rather than replacing the symbols themselves, it pokes at some other state during initialization.

**Comment by SimonSapin** [comment]
Then I suppose it would make sense. The question is, would there be a reason to want to control them separately?

**Comment by gnzlbg** [comment]
So this LGTM. @glandium, @Amanieu, thoughts? (you might want to check https://github.com/alexcrichton/jemallocator/pull/54 and https://github.com/alexcrichton/jemallocator/pull/53 for context).

**Comment by gnzlbg** [comment]
Thanks! If this needs tunning that can be done as new issues are discovered.

**Pull request merged**
